<?php
require_once __DIR__ . DIRECTORY_SEPARATOR . 'Partials' . DIRECTORY_SEPARATOR . 'html-start.php';
require_once __DIR__ . DIRECTORY_SEPARATOR . 'Partials' . DIRECTORY_SEPARATOR . 'navbar.php';
?>

<div class="container text-justify lh-lg">
    <div class="container my-5">
        <h2 class="font-primary">Normativas</h2>
        <p><a href="/docs/2024.4.30_Regimento_CEP_UNIJUI_revisao_APROVADO.docx.pdf" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Regimento do CEP UNIJUÍ</a></p>
        <p><a href="https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2024/lei/l14874.htm" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Lei nº 14.874, de 28 de maio de 2024.</a> Dispõe sobre a pesquisa com seres humanos e institui o Sistema Nacional de Ética em Pesquisa com Seres Humanos.</p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/biobancos/legislacao/portaria-no-2-201-de-14-de-setembro-de-2011" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Portaria MS nº 2.201, de 14 de setembro de 2011.</a> Estabelece as Diretrizes Nacionais para Biorrepositório e Biobanco de Material Biológico Humano com Finalidade de Pesquisa.</p>
    </div>

    <div class="container mt-5">
        <h2 class="font-primary">Resoluções</h2>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/legislacao/resolucoes/resolucao-no-251-de-07-de-agosto-de-1997" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Resolução nº 251, de 07 de agosto de 1997.</a> Aprova normas de pesquisa envolvendo seres humanos para a área temática de pesquisa com novos fármacos, medicamentos, vacinas e testes diagnósticos.</p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/legislacao/resolucoes/resolucao-no-292-de-08-de-julho-de-1999" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Resolução nº 292, de 08 de julho de 1999.</a> Pesquisas coordenadas do exterior ou com participação estrangeira e pesquisas que envolvam remessa de material biológico para o exterior.</p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/legislacao/resolucoes/resolucao-no-304-de-09-de-agosto-de-2000" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Resolução nº 304, de 09 de agosto de 2000.</a> Normas para pesquisas envolvendo seres humanos área de povos indígenas.</p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/legislacao/resolucoes/resolucao-no-340-de-8-de-julho-de-2004" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Resolução nº 340, de 8 de julho de 2004.</a> Diretrizes para Análise Ética e Tramitação dos Projetos de Pesquisa da Área Temática Especial de Genética Humana.</p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/legislacao/resolucoes/resolucao-no-346-de-13-de-janeiro-de-2005" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Resolução nº 346, de 13 de janeiro de 2005.</a> Tramitação de projetos de pesquisa multicêntricos.</p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/legislacao/resolucoes/resolucao-cns-no-441-de-12-de-maio-de-2011" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Resolução CNS nº 441, de 12 de maio de 2011.</a> Armazenamento de material biológico humano ou uso de material armazenado em pesquisas anteriores.</p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/legislacao/resolucoes/resolucao-no-466-de-12-de-dezembro-de-2012" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Resolução nº 466, de 12 de dezembro de 2012.</a> Diretrizes e normas regulamentadoras de pesquisas envolvendo seres humanos.</p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/legislacao/resolucoes/resolucao-no-506-de-03-de-fevereiro-de-2016" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Resolução nº 506, de 03 de fevereiro de 2016.</a> Acreditação dos Comitês de Ética em Pesquisa.</p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/legislacao/resolucoes/resolucao-no-510-de-07-de-abril-de-2016" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Resolução nº 510, de 07 de abril de 2016.</a> Normas aplicáveis a pesquisas em Ciências Humanas e Sociais.</p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/legislacao/resolucoes/resolucao-no-553-de-09-de-agosto-de-2017" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Resolução nº 563, de 10 de novembro de 2017.</a> Direito do participante de pesquisa com doenças ultrarraras.</p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/legislacao/resolucoes/resolucao-no-580-de-22-de-marco-de-2018" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Resolução nº 580, de 22 de março de 2018.</a> Pesquisas Estratégicas para SUS.</p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/legislacao/resolucoes/resolucao-no-647-de-12-de-outubro-de-2020" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Resolução nº 647, de 12 de outubro de 2020.</a> Dispõe sobre as regras referentes à regulamentação do processo de designação e atuação dos membros de CEP indicados por entidades do controle social.</p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/legislacao/resolucoes/resolucao-no-674-de-6-de-maio-de-2022" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Resolução nº 674, de 6 de maio de 2022.</a> Dispõe sobre a tipificação da pesquisa e a tramitação dos protocolos de pesquisa no Sistema CEP/Conep.</p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/legislacao/resolucoes/resolucao-no-706-de-16-de-fevereiro-de-2023" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Resolução nº 706, de 16 de fevereiro de 2023.</a> Dispõe sobre registro, credenciamento, renovação, alteração, suspensão e cancelamento do registro de Comitês de Ética em Pesquisa (CEPs) junto ao Sistema CEP/Conep, entre outras disposições.</p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/legislacao/resolucoes/2024/resolucao-no-738.pdf/view" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Resolução nº 738, de 01 de fevereiro de 2024.</a> Dispõe sobre uso de bancos de dados com finalidade de pesquisa científica envolvendo seres humanos.</p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/legislacao/norma/norma-operacional-no-001-de-2013.pdf/view" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Norma Operacional CNS nº 001/2013.</a> Organização e funcionamento do Sistema CEP/CONEP, e sobre os procedimentos para submissão, avaliação e acompanhamento da pesquisa e de desenvolvimento envolvendo seres humanos no Brasil.</p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/legislacao/oficios-circulares/oficio-circular-no-11-de-26-de-julho-de-2023.pdf/view" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Ofício Circular Conep nº 11, de 26 de julho de 2023.</a> Orientações relacionadas ao processo de obtenção do assentimento de participantes de pesquisa menores de 18 anos e de pessoas com "ausência de autonomia", permanente ou temporária, para consentir.</p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/legislacao/oficios-circulares/oficio-circular-no-16-de-4-de-julho-de-2022.pdf/view" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Ofício Circular Conep nº 16, de 4 de julho de 2022.</a> Tramitação de Protocolos de Pesquisa relativos ao SARS-CoV-2 (Covid-19).</p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/legislacao/oficios-circulares/oficio-circular-no-17-de-5-de-julho-de-2022.pdf/view" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Ofício Circular Conep nº 17, de 5 de julho de 2022.</a> Orientações acerca do artigo 1º da Resolução CNS n.º 510, de 7 de abril de 2016.</p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/legislacao/oficios-circulares/oficio-circular-no-23-de-17-de-outubro-de-2022.pdf/view" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Ofício Circular Conepnº 23, de 17 de outubro de 2022.</a> Normatização do uso de consentimento e assentimento eletrônico para participantes de pesquisa e de Biobancos.</p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/legislacao/oficios-circulares/oficio-circular-no-24-de-17-de-outubro-de-2022.pdf/view" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Ofício Circular Conep nº 24, de 17 de outubro de 2022.</a> Orientações gerais para a condução de ensaios clínicos.</p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/legislacao/oficios-circulares/oficio-circular-no-25-de-17-de-outubro-de-2022.pdf/view" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Ofício Circular Conep nº 25, de 17 de outubro de 2022.</a> Realização de reuniões do Sistema CEP/Conep em ambiente virtual.</p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/legislacao/oficios-circulares/oficio-circular-no-26-de-01-de-dezembro-de-2022.pdf/view" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Ofício Circular Conep nº 26, de 01 de dezembro de 2022.</a> Orientações para estudos com corpos ou peças anatômicas humanas.</p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/biobancos/legislacao/oficio-circular-no-34_21.pdf/view" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Ofício Circular Conep nº 34/2021.</a> Orientações para nova tramitação dos protocolos de desenvolvimento de biobancos para fins de pesquisa através da versão atual da Plataforma Brasil. </p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/legislacao/oficios-circulares/oficio-circular-no-16-de-4-de-julho-de-2022.pdf/view" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Ofício Circular Conep nº 16, de 4 de julho de 2022.</a> Tramitação de Protocolos de Pesquisa relativos ao SARS-CoV-2 (Covid-19).</p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/legislacao/oficios-circulares/oficio-circular-no-51-de-26-de-novembro-de-2024/view" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Ofício Circular Conep nº 51, de 26 de novembro de 2024.</a> Orientações sobre aspectos relacionados à aplicação da Lei nº 14.874, de 28 de maio de 2024.</p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/legislacao/oficios-circulares/oficio-circular-no-60-de-5-de-maio-de-2012.pdf/view" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Ofício Circular Conep nº 60, de 5 de maio de 2012.</a> Citação de bases de registro de ensaios clínicos em protocolos de pesquisa.</p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/legislacao/resolucoes" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Outras resoluções Conep</a></p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/legislacao/norma" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Normas Operacionais Conep</a></p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/legislacao/cartas-circulares" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Cartas circulares Conep</a></p>
        <p><a href="https://www.gov.br/conselho-nacional-de-saude/pt-br/acesso-a-informacao/sobre-o-conselho/camaras-tecnicas-e-comissoes/conep/legislacao/oficios-circulares" target="_blank" rel="external" class="font-primary fw-bold text-decoration-none">Ofícios circulares Conep</a></p>
    </div>
</div>

<?php
require_once __DIR__ . DIRECTORY_SEPARATOR . 'Partials' . DIRECTORY_SEPARATOR . 'html-end.php';
